# Generated by Django 5.2.4 on 2025-08-14 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("customer", "Customer"),
                    ("seller", "Seller"),
                    ("shipping_company", "Shipping Company"),
                    ("support_staff", "Support Staff"),
                ],
                max_length=20,
            ),
        ),
    ]
