# Generated by Django 5.2.4 on 2025-08-11 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_category_slug_alter_category_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                db_index=True, decimal_places=2, max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="title",
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
