# Generated by Django 5.2.4 on 2025-08-12 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "products",
            "0004_alter_product_is_active_alter_product_price_and_more",
        ),
        ("products", "0004_productreview"),
    ]

    operations = []
