# Generated by Django 5.2.4 on 2025-08-13 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_merge_20250812_1456"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="product",
            name="title",
            field=models.CharField(max_length=255),
        ),
    ]
